import React from 'react';
import { connect } from 'react-redux';
import { reduxFalcor } from 'utils/redux-falcor'
import Element from 'components/light-admin/containers/Element'
import {sendSystemMessage} from 'store/modules/messages';
import ReactFileReader from 'react-file-reader'
const csv = require('csv-parser')
const fs = require('fs')

const ATTRIBUTES = [
    //"id"
    "action_name",
    "action_number",
    "action_type",
    "description_of_problem_being_mitigated",
    "action_description",
    "associated_hazards",
    "metric_for_measurement",
    "name_of_associated_hazard_mitigation_plan",
    "date_of_lhmp_plan_approval",
    "action_county",
    "action_jurisdiction",
    "action_location",
    "action_located_in_special_flood_hazard_area",
    "action_located_in_hazard_zone",
    "recent_damages_incurred_at_action_locations",
    "action_point_of_contact",
    "poc_title",
    "contact_department_agency_or_organization",
    "lead_department_agency_or_organization",
    "action_partners",
    "alternative_action_1",
    "alternative_action_2",
    "no_alternative",
    "estimated_timeframe_for_action_implementation",
    "status",
    "is_pnp",
    "action_associated_with_critical_facility",
    "structure_type",
    "level_of_protection",
    "useful_life",
    "local_planning_mechanisms_in_implementation", // []
    "project_milestones",
    "estimated_cost_range",
    "calculated_cost",
    "population_served",
    "estimated_benefit_future_losses_avoided",
    "phased_action",
    "engineering_required",
    "bca",
    "primary_or_potential_funding_sources_type",
    "primary_or_potential_funding_sources_name",
    "secondary_funding_source_type",
    "secondary_funding_source_name",
    "funding_received_to_date",
    "associated_mitigation_capability",
    "associated_goals_objectives",
    "prioritization",
    "priority_scoring",
    "priority_scoring_funding_availability",
    "priority_scoring_probability_of_matching_funds",
    "priority_scoring_benefit_cost_review",
    "priority_scoring_environmental_benefit",
    "priority_scoring_technical_feasibility",
    "priority_scoring_timeframe_of_implementation",
    "plan_maintenance_date_of_status_report",
    "plan_maintenance_progress_report",
    "plan_maintenance_update_evaluation_of_problem_solution"
]

class ActionsUploadIndex extends React.Component {

    constructor(props){
        super(props)
        this.state = {
            data : []
        }
        this.confirmUpload = this.confirmUpload.bind(this)
        this.handleFiles = this.handleFiles.bind(this)

    }

    confirmUpload() {
        console.log('confirm')
    }
    handleFiles() {
        let reader = new FileReader();
        let fileArray = [];
        const selectedFile = document.getElementById('csvFile').files;
        reader.onload = (e) => {
            console.log('reader.result', reader.result)
            let res = reader.result;
            res = res.split('\t')
            let j = 0;
            for (let i = 0 ; i < res.length/ATTRIBUTES.length; i++){
                console.log('loop', i, j, j+ATTRIBUTES.length)
                fileArray.push(res.slice(j,j+ATTRIBUTES.length))
                j += (ATTRIBUTES.length - 1)
            }
            this.setState({'data': fileArray})
            return fileArray;
        }
        console.log('content', fileArray)

        reader.readAsText(selectedFile[0]);
    }

    render() {
        return(
            <div className='container'>
                <Element>
                    <h6 className="element-header">Upload Action project 1</h6>
                    {this.state.data.length > 0 ? (
                        <div>
                            <div className='col-sm-12' style={{'overflow': 'auto', 'maxHeight': '70vh', 'max-width': '80vw', 'display': 'block'}}>
                                <table className='table table lightBorder'>
                                    <thead>
                                    <tr>
                                        {ATTRIBUTES.map(f => <th style={{minWidth: '100%', position: 'sticky', top: '0', backgroundColor: '#CCC'}}> {f.split('_').join(' ')} </th>)}
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {this.state.data.map( row =>
                                        <tr> {row.map(cell => <td> {cell} </td>)} </tr>
                                    )}
                                    </tbody>
                                </table>
                            </div>
                            <div>
                                <button className="btn btn-primary step-trigger-btn" style={{height: '100%', position: 'sticky',
                                    float:'right', bottom:'10%', 'z-index': '100'}} onClick={this.confirmUpload}> Confirm Upload </button>
                            </div>
                        </div>
                    ) : <div>
                        <div className='table-responsive'>
                            <h8>Upload format: </h8>
                            <div className='col-sm-12' style={{'overflow': 'auto', 'maxHeight': '90vh', 'max-width': '90vw'}}>
                                <table className='table table lightBorder'>
                                    <thead>
                                    <tr>
                                        {ATTRIBUTES.map(f => <th style={{minWidth: '100%'}}> {f.split('_').join(' ')} </th>)}
                                    </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                        <div className='row'>
                            <div className="col-sm-6">
                                <input type='file' id='csvFile'/>
                                <button className="btn btn-primary step-trigger-btn" style={{height: '100%'}} onClick={this.handleFiles}> Upload </button>
                            </div>
                        </div>
                    </div>
                    }
                </Element>
            </div>
        )

    }
}

const mapStateToProps = state => ({
    isAuthenticated: !!state.user.authed,
    attempts: state.user.attempts, // so componentWillReceiveProps will get called.
});

const mapDispatchToProps = {
    sendSystemMessage
};

export default [
    {
        path: '/actions/project/upload/',
        exact: true,
        name: 'ActionsUpload',
        auth: true,
        mainNav: false,
        breadcrumbs: [
            { name: 'Actions Upload', path: '/actions/project/' },
        ],
        menuSettings: {
            image: 'none',
            scheme: 'color-scheme-light',
            position: 'menu-position-left',
            layout: 'menu-layout-compact',
            style: 'color-style-default'
        },
        component: connect(mapStateToProps,mapDispatchToProps)(ActionsUploadIndex)
    }
]

/*
Action Name,Action Number,Action Type,Description of Problem being Mitigated,Action Description,Associated Hazard(s),Metric for measurement,Name of Associated Hazard Mitigation Plan,Date of HMP plan approval,Action County,Action Jurisdiction,Action Location,Action Located in Special Flood Hazard Area (SFHA)?,Action Located in Hazard Zone?,Recent Damages Incurred at Action Location ($),Action Point of Contact,POC Title,"Contact Department, Agency or Organization","Lead Department, Agency or Organization",Action Partners,Alternative Action 1,Alternative Action 2,No Alternative,Estimated Timeframe for Action Implementation,Status,Is PNP,Action associated with a critical facility?,Structure Type,Level of Protection,Useful Life,Local Planning Mechanisms (via capabilities) to be Used in Implementation,Project Milestones,"Cost Range, H/M/L",Estimated Cost Range,Calculated Cost,Population Served,Estimated Benefit (Future Losses Avoided),Phased Action?,Engineering Required?,BCA,Primary or Potential Funding Sources Type,Primary or Potential Funding Source Name,Secondary Funding Source Type,Secondary Funding Source Name,Funding Received to Date,Associated Mitigation Capability,Associated Goal(s)/Objective(s),Prioritization,Priority Scoring: Probability of Acceptance by Community,Priority Scoring: Funding Availability,Priority Scoring: Probability of Matching Funds,Priority Scoring: Benefit Cost Review,Priority Scoring: Environmental Benefit,Priority Scoring: Technical Feasibility,Priority Scoring: Timeframe of Implementation,Plan Maintenance - Date of Status Report,Plan Maintenance - Progress Report,Plan Maintenance - Update Evaluation of the Problem an/or Solution
text entry,text entry,Action Type from SHMP,text entry,text entry,drop down,,,,Automated based on county plan,selected from dropdown (includes municipalities and county),,can it be populated from EBR based on location,can it be populated from EBR based on location,numerical entry,select from dropdown or add new contact - opens contact entry form,comes with contact info,comes with contact info,comes with contact info,text entry,text entry,text entry,text entry,,"Select status dropdown: Ongoing, discontinued, completed, in-progress",,yes/no,drop down,,numerical,capabilities dropdown - multiselect,text entry,"cost range: high, medium, low","cost ranges: <$100K, $100K-$500K, $500K-$1M, $1M-$5M, $5M-$10M, $10M+",numerical,"range: 0-50, 50-100, 100-1,000, 1,000+, Jurisdictional","BCA Calculations, this will come from municpal data + EBR data",yes/no,yes/no,BCA document upload?,"Dropdown Funding Source Types: Federal, State, Local, Private","From Dropdown List populated by selection from funding source type (federal, state etc.)","Dropdown Funding Source Types: Federal, State, Local, Private","From Dropdown List populated by selection from funding source type (federal, state etc.)",,,,Total Score from the Prioritization Self-Assessment,"(0) Would be strongly opposed by nearly all of the population, (1) Would be strongly opposed by special interest groups or a significant percentage of the population, (2) Would be somewhat controversial with special interest groups or a small percentage of the population, (3) Of benefit only to those directly affected and would not adversely affect others, (4) Likely to be endorsed by the entire population","0) Potential funding source unknown, (1) Grant fudning needed, (2) Grant funding identified, (3) Can be funded by operating budget, (4) Little to no direct expenses","0) No funding match available or funding match unknown, (2) Partial funding match available, (4) Funding match is available of funding match not required","0) Benefit Cost Review unknown, (2) Benefit Cost Review not required, 4) Likely to meet Benefit Cost Review","0) Very difficult to implement due to extremely complex requirements and environmental permitting problems, 1) Difficult to implement because of significantly complex requirements and environmental permitting, 2) Environmental concerns and somewhat difficult to implement because of complex requirements, 3) Environmentally acceptable and not anticipated to be difficult to implement, 4) Environmentally sound and relatively easy to implement; or no adverse impact on environment.","0) Technical feasibility unknown or additional information needed, 2) Expected to be technically feasibled, 4) Proven to be technically feasible ","0) More than 5 years (Long-Term), 2) 2 – 5 years (Long-Term), 4) 1 year or less (Short Term)",date entry,text entry,text entry
,,,"Provide a detailed narrative of the problem. Describe the natural hazard you wish to mitigate, its impacts to the community, past damages and loss of service, etc. Include the street address of the property/project location (if applicable), adjacent streets, and easily identified landmarks such as water bodies and well-known structures, and end with a brief description of existing conditions (topography, terrain, hydrology) of the site.","Provide a detailed narrative of the solution.  Describe the physical area (project limits) to be affected, both by direct work and by the project's effects; how the action would address the existing conditions previously identified; proposed construction methods, including any excavation and earth-moving activities; where you are in the development process (e.g., are studies and/or drawings complete), etc., the extent of any analyses or studies performed (attach any reports or studies).",Identify the hazard being addressed with this action. ,,,,,,,,,,,,,,,,,,,,,,New/Existing/Both/Neither,Identify the level of protection the proposed project will provide.  Ex. 100-year (1%) flood.,Identify the number of years the proposed project will provide protection against the hazard.,,,,,,,,,,,,,,,,,,,,,,,,,,This section should be completed during plan maintenance/evaluation.,"Describe what progress, if any, has been made on this project.  If it has been determined the community no longer wishes to pursue implementation, state that here and indicate why.","Provide an updated description of the problem and solution, and what has happened since initial consideration/development."
Distribute information to public on ways to build homes to withstand tornados/high winds,,Education and outreach,,Distribute information to public on ways to build homes to withstand tornados/high winds,"Tornado, Severe Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,,,,,County Emergency Management (lead),County Emergency Management,County Emergency Management,DPEM,,,,Short,,,,New,,,,,Low,"estimated to be below $10,000",,,N/A,,,,Federal,FEMA Mitigation Grant,,,,,"4, 6",,,,,,,,,,,
Regularly assess conditions of railroad infrastructure,,Risk/Vulnerability Assessment,,Initiate coordination with railway owners to regularly assess conditions of railroad infrastructure,"Haz Mat, Transpo. Accidents",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,,,,,County Emergency Management (lead),County Emergency Management,County Emergency Management,LEPC,,,,Long,,,yes,Existing,,,,,Low,"estimated to be below $10,000",,,,,,,County,County Funds,,,,,1,,,,,,,,,,,
Stormwater training for planning boards,,Prevention/Mitigation projects,,Continue existing County SWCD flood remediation program,"Flood, Landslide, Structural Collapse",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes (?),,,County DPW,County DPW,County DPW,DPEM,,,,Moderate,,,yes,Existing and new,,,,,Moderate,"estimated between $10,000 and $100,000",,,,,,,"County, State","SWCD, County Funds, State Grant",,,,,"4,6",,,,,,,,,,,
Town Highway 39 - Bridge #293 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2010,,yes,Existing,,,,,High,$1M-$5M,"$2,681,498.00",,,,,,"County, State, Federal","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 55 - Bridge #3 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,Yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2010,,Yes,Existing,,,,,High,$500K-$1M,"$900,000",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 53 - Bridge #47 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,Yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2010,,Yes,Existing,,,,,High,$100K-$500K,"$100,000",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 103 - Bridge #109 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated complettion; 2011,,yes,Existing,,,,,High,$100K-$500K,"$100,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 13- Bridge #251 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated complettion; 2011,,yes,Existing,,,,,High,$100K-$500K,"$320,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 1- Bridge #263 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DpW,,,,,Long,estimated complettion; 2011,,yes,Existing,,,,,High,$500K-$1M,"$750,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 56- Birdge #461 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,ys,yes,,,County DPW,County DPW,County DPW,,,,,long,estimated complettion; 2011,,yes,Existing,,,,,High,$100K-$500K,"$100,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 17- Bridge #241 Replacement Including Flood Mit. Improvement,,Prevention/Mitigation projects,,SUllivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2012,,yes,existing,,,,,High,$100K-$500K,"$320,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 77- Bridge #427 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2012,,yes,Existing,,,,,High,$100K-$500K,"$320,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 105- Bridge #462 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2012,,yes,Existing,,,,,High,$100K-$500K,"$100,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 55- Bridge #36 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2012,,yes,Existing,,,,,High,$100K-$500K,"$250,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 73- Bridge #252 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2012,,yes,existing,,,,,High,$100K-$500K,"$100,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 23- Bridge #76 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2013,,yes,Existing,,,,,High,$1M-$5M,"$1,000,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 32- Bridge #268 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2013,,yes,Existing,,,,,High,$100K-$500K,"$280,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 38- Bridge #261 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2013,,yes,Existing,,,,,High,$100K-$500K,"$280,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 61- Bridge #313 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2013,,yes,Existing,,,,,High,$100K-$500K,"$320,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 98- Bridge #428 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2013,,yes,Existing,,,,,High,$100K-$500K,"$280,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 53- Bridge #45 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2014,,yes,Existing,,,,,High,$1M-$5M,"$2,240,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 176- Bridge #379 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2014,,yes,Existing,,,,,High,$100K-$500K,"$200,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 164- Kohlertown Flood Mitigation Project,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2014,,yes,Existing,,,,,High,$1M-$5M,"$1,500,00.00",,,,,,,,,,,,"1,2",,,,,,,,,,,
County Road 55- Bridge #29 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2014,,yes,Existing,,,,,High,$100K-$500K,"$350,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 21- Bridge #272 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2014,,yes,Existing,,,,,High,$100K-$500K,"$280,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 48- Bridge #98 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2014,,yes,Existing,,,,,High,$100K-$500K,"$320,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Maple Ave - Bridge #22 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2015,,yes,Existing,,,,,High,$100K-$500K,"$210,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 47- Bridge #228 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2015,,yes,Existing,,,,,High,$100K-$500K,"$224,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 22- Bridge #270 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2015,,yes,Existing,,,,,High,$100K-$500K,"$196,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 28- Bridge #430 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2015,,yes,Existing,,,,,High,$100k-$500K,"$196,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Town Highway 39- Bridge #192 Replacement Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2015,,yes,Existing,,,,,High,$1M-$5M,"$2,800,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 92- Pipe Upgrades/Addit. Crossers/Debris Rack - Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2010,,yes,Existing,,,,,High,<$100K,"$75,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 123- Pipe Upgrades/Addit. Crossers/Debris Rack - Flood Mit Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,CountyD,County DPW,,,,,Long,estimated completion; 2010,,yes,Existing,,,,,High,<$100K,"$80,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 153- Road/River Embankment Stabilization/Fortification,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2010,,yes,Existing,,,,,High,$100K-$500K,"$125,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 178- Road/River Embankment Stabilization/Fortification (FEMA 1650),,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DpW,County DPW,,,,,Long,estimated completion; 2010/2011,,yes,Existing,,,,,High,$100K-$500K,"$250,00.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 17- Close Drainage System Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2011,,yes,Existing,,,,,High,$500K-$1M,"$750,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 164- Closed Drainage System (Phase II) Incl. Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2011,,yes,Existing,,,,,High,$500K-$1M,"$550,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 179- Road Embankment Stabilization,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2011,,yes,Existing,,,,,High,$100K-$500K,"$100,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 47 - Closed Drainage System Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2012,,yes,Existing,,,,,High,$500K-$1M,"$500,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 94 - Major Road/River Embankment Stabilization/Fortification,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2012,,yes,Existing,,,,,High,$1M-$5M,"$1,500,000.00",,,,,,,,,,,,"1,2",,,,,,,,,,,
County Road 113- Closed Drainage System Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2013,,yes,Existing,,,,,High,$100K-$500K,"$300,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 121 - Road/River Embankment Stabilization/Fortification,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2013,,yes,Existing,,,,,High,$100K-$500K,"$250,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 15 - Closed Drainage System Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2014,,yes,Existing,,,,,High,$100K-$500K,"$300,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 14/141- Closed Drainage System Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2015,,yes,Existing,,,,,High,$100K-$500K,"$400,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 121/122 - Closed Drainage System Including Flood Mit. Improvements,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2015,,yes,Existing,,,,,High,$100K-$500K,"$350,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
County Road 134 - Road Embankment Stabilization,,Prevention/Mitigation projects,,Sullivan County transportation improvement projects to reduce flooding impacts,"Flood, Severe Storm, Tornado, Transp. Accident, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,yes,yes,,,County DPW,County DPW,County DPW,,,,,Long,estimated completion; 2015,,yes,Existing,,,,,High,$100K-$500K,"$250,000.00",,,,,,"County, State, Federal (?)","DOT, FHWA, County Budget",,,,,"1,2",,,,,,,,,,,
Continue to provide DEC stream permitting assistance to municipalities ,,,,Helps ensure appropriate development considerations,,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,County,,,,,,County DPW,County DPW,County DPW,,,,,Short,,,,,,,,,,,,,,,,,County,"SWCD, County Funds",,,,,,,,,,,,,,,,
"Improvement to Brook Rd, Ballard Rd, Burr Rd, West Shore Rd, Wormuth Rd, Laird Rd ",,Prevention/Mitigation projects,,"Improve Brook Rd, Ballard Rd, Burr Rd, West Shore Rd, Wormuth Rd, Laird Rd to minimize flooding impacts to roadway and adj property","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Bethel,"Brook Rd, Ballard Rd, Burr Rd, West
 Shore Rd, Wormuth Rd, Laird Rd",yes,yes,,,Town of Bethel DPW/Highway Dept.,Town of Bethel DPW/Highway Dept.,Town of Bethel DPW/Highway Dept.,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Federal, Local (Muni.)","DOT, FHWA, Municipal Budget",,,,,"1,2",,,,,,,,,,,
Acquire emergency generator(s) ,,Prevention/Mitigation projects,,"Acquire emergency generators for Town Hall, Highway garage, Justice Court, and Senior Center",Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Bethel,"Town Hall, Highway garage, Justice Court and Senior Center",,,,,SCEMP/LEPC,SCEMP/LEPC,SCEMP/LEPC,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Complete dam assessment ,,Risk/Vulnerability Assessment,,Complete dam assessment within Town to determine condition of structures,Dam Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Bethel,,yes,yes,,,"Town Board, Town Planning Board","Town Board, Town Planning Board","Town Board, Town Planning Board",,,,,Moderate,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), State","NYSDEC, Municipal Budget",,,,,"2,5",,,,,,,,,,,
Initiate maintenance program ,,Prevention/Mitigation projects,,Initiate maintenance program remove debris jams from Earl Myers Bridge Rd,"Dam Failure, Flood, Structural Collapse",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Callicoon,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Moderate,,,yes,Existing,,,,,Low,,,,,,,,"Federal, County","FEMA, County Funds",,,,,"2,3",,,,,,,,,,,
"Replace/rehab Youngsville NYS Bridge/ Route 52, Dewitts Flats and maintain/ analyze drainage system to reduce flood impacts",,Prevention/Mitigation projects,,"Replace/rehab Youngsville NYS Bridge/ Route 52, Dewitts Flats and maintain/ analyze drainage system to reduce flood impacts","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Callicoon,,yes,yes,,,Town DPW/Highway/DOT,Town DPW/Highway/DOT,Town DPW/Highway/DOT,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Budget",,,,,"1,2",,,,,,,,,,,
Utility tree trimming and private property tree maintenance,,Risk/Vulnerability Assessment,,Increase and promote utility tree trimming and private property tree maintenance,"Earthquake, Structural Collapse, Tornado, Utility Failure, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Callicoon,,,,,,Town Emergency Response and Planning,Town Emergency Response and Planning,Town Emergency Response and Planning,,,,,Short,,,,Existing and new buildingd and infrastructure,,,,,Low,,,,,,,,"Local (Muni.), State, Federal","Municipal Budget, State Grant, HMGP",,,,,"4,6",,,,,,,,,,,
Feasibility assessment,,Risk/Vulnerability Assessment,,Feasibility assessment of exending water and sewer districts,"Drought, Civil Unrest",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Callicoon,,no,no,,,Town Board,Town Board,Town Board,,,,,Long,,,no,Existing and new buildingd and infrastructure,,,,,moderate,,,,,,,,"Local (Muni.), County, State, Federal","State Grant, Municipal Budget, County Funds, USDA",,,,,"5,6",,,,,,,,,,,
Implement stormwater management plan ,,Planning and Regulatory,,Implement stormwater management plan requrement during Planning Board review,"Flood, Landslide, structural collapse",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Callicoon,,,,,,Town Planning and Zoning Board,Town Planning and Zoning Board,Town Planning and Zoning Board,,,,,Short,,,,New,,,yes,,Low,,,,,,,,No Funding Required,,,,,,"2,5",,,,,,,,,,,
Acquire emergency generator(s),,Planning and Regulatory,,Acquire emergency generators for firehouses and ambulance buildings,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Callicoon,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Nudget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Distribute information to public about hazard preparation,,Technical assistance,,Distribute mailings and electronic information to public about hazard preparation,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Callicoon,,,,,,Town Emergency Response and Town Information Center,Town Emergency Response and Town Information Center,Town Emergency Response and Town Information Center,,,,,Short,,,,Existing and new,,,yes,,Low,,,,,,,,Local (Muni.),Municipal Budget,,,,,"4,6",,,,,,,,,,,
Acquire emergency generator(s) ,,Technical assistance/program management,,Acquire emergency generator for Town Hall,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Cochecton,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Regularly assess conditions of railroad infrastructure,,Planning and Regulatory,,Initiate coordination with railway owners to regularly assess conditions of railroad infrastructure,"Haz Mat, Transpo. Accidents",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Cochecton,,,yes,,,"Town Board, Emergency Response","Town Board, Emergency Response","Town Board, Emergency Response",,,,,Long,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), County","County Funds, Municipal Budget",,,,,1,,,,,,,,,,,
Improve highway radio communication system,,Technical assistance,,Improve highway radio communication system,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Cochecton,,,,,,Emergency Management,Emergency Management,Emergency Management,,,,,Long,,,no,Existing and new,,,,,High,,,,,,,,"Local (Muni.), County","Municipal Budget, County Budget",,,,,4,,,,,,,,,,,
"Replace/rehab Main St/Beechwood Rd, CR 164 and CR 52 to reduce flooding issues",,Prevention/Mitigation projects,,"Replace/rehab Main St/Beechwood Rd, CR 164 and CR 52 to reduce flooding issues","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Delaware,,yes,yes,,,"Town of Delaware, County DPW","Town of Delaware, County DPW","Town of Delaware, County DPW",,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Budget",,,,,"1,2",,,,,,,,,,,
Regularly assess conditions of railroad infrastructure,,Technical assistance/program management,,Initiate coordination with railway owners to regularly assess conditions of railroad infrastructure,"Haz Mat, Transpo. Accidents",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Delaware,,,yes,,,Emergency Management,Emergency Management,Emergency Management,,,,,Long,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), County","County Funds, Municipal Budget",,,,,1,,,,,,,,,,,
Implement flood mitigation measures,,Prevention/Mitigation projects,,"Implement flood mitigation measures (resize culverts, complete stream assessments) in the Kohlertown area to aleviate flooding issues and impacts to residents, businesses and infrastructure","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Delaware,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), Federal, State","DOT, FHWA, Municipal Budget",,,,,"1,2",,,,,,,,,,,
Acquire generator(s),,Technical assistance/program management,,Acquire generators for multiple critical facilities,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Fallsburg,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Resize/upgrade culverts to reduce damage from flooding,,Prevention/Mitigation projects,,"Resize/upgrade culverts on Marsh Rd, Mongaup Rd, and Maplewood Dr to box culverts to reduce damage from flooding","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Fallsburg,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), Federal, State","DOT, FHWA, Municipal Budget",,,,,"1,2",,,,,,,,,,,
Bank stabilization and/or culvert upgrade,,Prevention/Mitigation projects,,Bank stabilization and/or culvert upgrade to help prevent Couzines Rd (seasonal dirt rd) from being washed out during flood events,"Flood, Severe Storm, Winter Storm, Landslide",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Fallsburg,,yesy,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Long,,,yes,Exisiting,,,,,High,,,,,,,,Local (Muni.),Municipal Budget,,,,,"1,2",,,,,,,,,,,
Replace/rehab roads/bridges to minimize flood damage,,Prevention/Mitigation projects,,"Replace/rehab Mill Rd Bridge, CR 44 & French, Rt 42/43 crossing to minimize flood damagae","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Forestburgh,,yes,yes,,,"Town DPW/Highway, DOT","Town DPW/Highway, DOT","Town DPW/Highway, DOT",,,,,Long,,,,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Funds",,,,,"1,2",,,,,,,,,,,
Implement maintenance program,,Planning and Regulatory,,Implement maintenance program for debris removal at CR 44 and French St.,"Dam Failure, Flood, Ice Jam",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Forestburgh,,yes,yes,,,"Town DPW/Highway, Emergency Response","Town DPW/Highway, Emergency Response","Town DPW/Highway, Emergency Response",,,,,moderate,,,,Existing and New,,,,,Moderate,,,,,,,,"Local (Muni.), State, Federal","HMGP, SWCD, State Grant",,,,,"2,3,5",,,,,,,,,,,
Complete dam assessment,,Risk/Vulnerability Assessment,,Complete dam assessment of Lake Joseph dam,dam failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Forestburgh,,yes,yes,,,"Town Board, Town Planning Board","Town Board, Town Planning Board","Town Board, Town Planning Board",,,,,Moderate,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), State","NYSDEC, Municipal Budget",,,,,"2,5",,,,,,,,,,,
Culvert Upgrade to reduce flood damage,,Prevention/Mitigation projects,,Deer Lake Road Culvert upgrade to reduce flood damage,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Fremont,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), Federal, State","DOT, FHWA, Municipal Budget",,,,,"1,2",,,,,,,,,,,
Replace/rehab roads/bridges to minimize flooding,,Prevention/Mitigation projects,,"Replace/rehab Friedenstein Rd & Basket Rd, Deer Lake Rd, Town Rd #10 & Buck Brook Rd to minimize flooding","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,Town of Fremont,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Funds",,,,,"1,2",,,,,,,,,,,
Regularaly assess conditions of railroad infrastructures,,Technical assistance/program management,,Initiate coordination with railway owners to regularaly assess conditions of railroad infrastructures,"Haz Mat, Transpo. Accidents",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Fremont,,,yes,,,Emergency Management,Emergency Management,Emergency Management,,,,,Long,,,yes,Exising,,,,,Moderate,,,,,,,,"Local (Muni.), County","County Funds, Municipal Budget",,,,,1,,,,,,,,,,,
Complete dam assessment,,Risk/Vulnerability Assessment,,Complete dam assessment of Muskoday dam,Dam Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Fremont,,yes,yes,,,"Town Board, Town Planning Board","Town Board, Town Planning Board","Town Board, Town Planning Board",,,,,Moderate,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), State","NYSDEC, Municipal Budget",,,,,"2,5",,,,,,,,,,,
Culvert replacement to minimize flooding,,Prevention/Mitigation projects,,Airport Road/Levenworth Road area culvert replacement to minimize flooding,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Highland,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Moderate,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Budget",,,,,"1,2",,,,,,,,,,,
Acquire emergency generator(s),,Technical assistance/program management,,Acquire emergency generators for multiple critical facilities,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,Town of Highland,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Establish response communication system,,Technical assistance/program management,,Establish own municipal response communication system,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Highland,,,,,,"Emergency Management, Emergency Response","Emergency Management, Emergency Response","Emergency Management, Emergency Response",,,,,Long,,,,Existing and new,,,,,High,,,,,,,,"Local (Muni.), County","Municipal Budget, County Budget",,,,,4,,,,,,,,,,,
Replace/rehab roads/bridges to reduce flood impacts,,Prevention/Mitigation projects,,"Replace/rehab Airport Rd, Aden Rd to reduce flood impacts","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Liberty,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Budget",,,,,"1,2",,,,,,,,,,,
Acquire emergency generator(s),,Technical assistance/program management,,Acquire emergency generators for firehouses and town ban,Utility Failure,,SUllivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Liberty,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Complete dam assessment,,Risk/Vulnerability Assessment,,Complete dam assessment for dams in town to determine structural integrity,Dam Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Liberty,,yes,yes,,,"Town Board, Town Planning Board","Town Board, Town Planning Board","Town Board, Town Planning Board",,,,,Moderate,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), State","NYSDEC, Municipal Budget",,,,,"2,5",,,,,,,,,,,
Utility tree trimming and private property tree maintenance,,Risk/Vulnerability Assessment,,Increase and promote utility tree trimming and private property tree maintenance,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Liberty,,,,,,Town Emergency Response and Planning Board,Town Emergency Response and Planning Board,Town Emergency Response and Planning Board,,,,,Moderate,,,,Existing and New,,,,,Low,,,,,,,,"Local (Muni.), State, Federal","Municipal Budget, HMGP",,,,,"1,2,4,5,6",,,,,,,,,,,
Educational mailings sent to public on potential hazards,,Education and outreach,,Educational mailings sent to public on potential hazards,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Lumberland,,,,,,Town Emergency Response and Town Information Center,Town Emergency Response and Town Information Center,Town Emergency Response and Town Information Center,,,,,Short,,,,Existing and new,,,yes,,Low,,,All,,,,,Local (Muni.),Municipal Budget,,,,,"4,6",,,,,,,,,,,
Replace/rehab roads/bridges to reduce impacts from flood events,,Prevention/Mitigation projects,,"Replace/rehab Rt 97, Hollow Rd, Sweeny Rd to reduce impacts from flood events","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Lumberland,,yes,yes,,,"Town DPW/Highway, DOT","Town DPW/Highway, DOT","Town DPW/Highway, DOT",,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), State, Federal","DOT, FHWA, Municipal Budget",,,,,"1,2",,,,,,,,,,,
Acquire emergency generator(s),,Technical assistance/program management,,Acquire emergency generator for Town Hall,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Lumberland,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Dam failure analysis ,,Risk/Vulnerability Assessment,,Complete dam failure analysis for Rio Dam,Dam Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Lumberland,,yes,yes,,,"Town Board, Town Planning Board","Town Board, Town Planning Board","Town Board, Town Planning Board",,,,,Moderate,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), State","NYSDEC, Municipal Budget",,,,,"2,5",,,,,,,,,,,
Replace/rehab roads/bridges to minimize flooding issues,,Prevention/Mitigation projects,,Replace/rehab Philipsport Rd Bridge to minimize flooding issues,Flood,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Mamakating,,,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal/County Budget",,,,,"1,2",,,,,,,,,,,
Complete assessment study to determine improvements that can be made to alleviate flooding impacts,,Education/Prevention,,Pine Kill Road Stream mitigation - complete assessment study to determine improvements that can be made to alleviate flooding impacts,"Dam Failure, Flood, Ice Jam",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Mamakating,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Moderate,,,yes,Existing and new,,,,,Moderate,,,,,,,,"State, Federal","HMGP, SWCD, State Grant",,,,,"2,3,5",,,,,,,,,,,
Response radio communication system,,Technical assistance/program management,,Improve highway/emergency response radio communication system,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Neverink,,,,,,Emergency Management,Emergency Management,Emergency Management,,,,,Long,,,,Existing and new,,,yes,,High,,,,,,,,"Local (Muni.), County","Municipal Budget, County Budget",,,,,4,,,,,,,,,,,
Acquire emergency generator(s),,Technical assistance,,Acquire emergency generator for Tri-Valley Central School (Red Cross shelter location),Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Neverink,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Distribute informationon flood-proofing properties/homes,,Education and outreach,,Put together and distribute information to public on flood-proofing private property and homes and making retrofits to reduce flooding impacts,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Neverink,,,,,,Town Planning and Town Information Officer,Town Planning and Town Information Officer,Town Planning and Town Information Officer,,,,,Short,,,no,Existing and new,,,yes,,Low,,,,,,,,"Local (Muni.), County, State","Municipal Budget, State Grant, County Funds",,,,,"4,6",,,,,,,,,,,
Replace/rehab roads/bridges to reduce flood impacts,,Prevention/Mitigation projects,,replace/rehab Hardy St to reduce flood impacts,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Rockland,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Moderate,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Budget",,,,,"1,2",,,,,,,,,,,
Acquire emergency generator(s),,Technical assistance/program management,,"Acquire emergency generator for Town Hall, firehouses, and ambulance buildings",Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Rockland,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Install backflow valve,,Prevention/Mitigation projects,,Install backflow valve for catch basin on Pearl St.,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Rockland,,yes,yes,,,"Town DPW/Highway, Town Board","Town DPW/Highway, Town Board","Town DPW/Highway, Town Board",,,,,Long,,,yes,Existing,,,,,Moderate,,,,,,,,Local (Muni.),Municipal Budget,,,,,"2,5",,,,,,,,,,,
ACOE recommendatins,,Prevention/Mitigation projects,,Livingston Manor Flooding- ACOE recommendatins,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Rockland,,yes,yes,,,Town Board,Town Board,Town Board,SWCD,,,,Long,,,yes,Existing and new,,,,,High,,,,,,,,Federal,"Federal Grant, HMGP",,,,,"2,5",,,,,,,,,,,
Bank stabilization,,Prevention/Mitigation projects,,Bank stabilization on Willoemoc Rd.,"Flood, Severe Storm, Landslide, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Rockland,,yes,yes,,,Town Board,Town Board,Town Board,SWCD,,,,Long,,,yes,Existing and new,,,,,Moderate,,,,,,,,"Local (Muni.), State","SWCD Grant, Municipal Budget, State Grant",,,,,"2,3,5",,,,,,,,,,,
Enlarge catch basin system,,,,Enlarge catch basin system on Highland Ave,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Rockland,,yes,yes,,,"Town DPW/Highway, Town Planning","Town DPW/Highway, Town Planning","Town DPW/Highway, Town Planning",,,,,Long,,,yes,Existing,,,,,Moderate,,,,,,,,Local (Muni.),Municipal Budget,,,,,"2,5",,,,,,,,,,,
Acquire generator (s),,Technical assistance,,Acquire generators for Town Hall/Community Center,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Thompson,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,Yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Upgrade culverts,,Prevention/Mitigation projects,,Upgrade culverts at Tucci Road crossing to alleviate reoccurring flood damage,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Thompson,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), State, Federal","DOT, FHWA, Municipal Budget",,,,,"1,2",,,,,,,,,,,
Replace/rehab roads/bridges to reduce flood damage,,Prevention/Mitigation projects,,Replace/rehab Lake Erie Bridge and Swamp Pond Road to reduce flood damage,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Tusten,,yes,yes,,,Town DPW/Highway,Town DPW/Highway,Town DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), State, Federal","DOT, FHWA, Municipal/County Budget",,,,,"1,2",,,,,,,,,,,
Erect emergency tower,,Technical assistance,,Erect emergency tower to inform public of disaster events,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Tusten,,,,,,"Town Board, Emergency Management","Town Board, Emergency Management","Town Board, Emergency Management",,,,,Long,,,,Existing and new,,,,,high,,,,,,,,"State, Federal","HMGP,State Grant",,,,,"4,5",,,,,,,,,,,
Regularaly assess conditions of railroad infrastructures,,Technical assistance/program management,,Initiate coordination with railway owners to regularaly assess conditions of railroad infrastructures,"Haz Mat, Transpo. Accidents",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Tusten,,,yes,,,"Town Board, Emergency Response","Town Board, Emergency Response","Town Board, Emergency Response",,,,,Long,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), County","County Funds, Municipal Budget",,,,,1,,,,,,,,,,,
Expand public water for fire suppression needs,,,,Expand public water for fire suppression needs,"Drought, Fire",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Tusten,,,yes,,,"Town Board, Town Planning & Engineer","Town Board, Town Planning & Engineer","Town Board, Town Planning & Engineer",,,,,Long,,,yes,Existing and new,,,,,High,,,,,,yes,,"State, Federal","State Grant, USDA",,,,,"4,5",,,,,,,,,,,
Acquire emergency generator(s),,Technical assistance/program management,,Acquire emergency generators for multiple critical facilities,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Tusten,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Improve communication system(s),,Technical assistance,,Improve communication system for emergency responders,all Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Tusten,,,,,,Emergency Management and Response,Emergency Management and Response,Emergency Management and Response,,,,,Long,,,yes,Existing and new,,,yes,,High,,,,,,,,"State, Federal","HMGP,State Grant",,,,,"4,5",,,,,,,,,,,
Emergency evacuation protocol and shelter location,,Planning and Regulatory,,Establish emergency evacuation protocol and shelter location,all Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"Octcober, 2012",Sullivan,Town of Tusten,,,,,,"Emergency management, Town Planning","Emergency management, Town Planning","Emergency management, Town Planning",,,,,Short,,,yes,Existing buildings and infrastructure,,,yes,,Low,,,,,,,,County,County Budget,,,,,4,,,,,,,,,,,
Implement stormwater management plan,,Planning and Regulatory,,Implement stormwater management plan requirement during Planning Board review,"Flood, Landslide, Structural Collapse",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Tusten,,yes,yes,,,"Town Board, Planning & Zoning","Town Board, Planning & Zoning","Town Board, Planning & Zoning",,,,,Short,,,yes,New,,,yes,,Low,,,,,,,,No Funding Required,,,,,,"2,6",,,,,,,,,,,
Protocol for structures in flood area,,Risk/Vulnerability Assessment (and planning?),,Review current protocol for siting of structures in flood area,"Flood, Severe Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Town of Tusten,,yes,yes,,,"Town Board, Town Planning, Town Codes","Town Board, Town Planning, Town Codes","Town Board, Town Planning, Town Codes",,,,,Moderate,,,yes,New,,,yes,,Low,,,,,,,,No Funding Required,,,,,,"2, 5",,,,,,,,,,,
Incorporate smart site planning and hazard reduction elements,,Planning and Regulatory,,Incorporate smart site planning and hazard reduction elements for new development projects through modifications to planning board review checklist/criteria,"Flood, Lanslide",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Bloomingburg,,,,,,Village Planning,Village Planning,Village Planning,,,,,Moderate,,,,New,,,yes,,Moderate,,,,,,,,"Local (Muni.), Federal","Municipal Budget, HMGP",,,,,"2,3,5",,,,,,,,,,,
Inform public about hazard vulnerabilities,,Education and outreach,,Campaign to inform public about hazard vulnerabilities within Village through distribution of promotional materials during community events and posting of tips and other information on municipal website,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Bloomingburg,,,,,,Emergency Management and Village Board,Emergency Management and Village Board,Emergency Management and Village Board,,,,,Short,,,,Existing and new,,,yes,,Low,,,,,,,,"Local (Muni.), State, County","Municipal Budget, State Grant, County Funds",,,,,"4,6",,,,,,,,,,,
Install stormwater drainage system,,Prevention/Mitigation projects,,Install stormwater drainage system,"Dam Failure, Flood, Landslide, Structural Collapse, Utility Failure",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Jeffersonville,,yes,yes,,,"Village Board, Engineer","Village Board, Engineer","Village Board, Engineer",,,,,Long,,,yes,Existing and new,,,,,High,,,,,,,,"State, Local (Muni.)","Municipal Budget, State Grant",,,,,"2,4,5",,,,,,,,,,,
Upgrade signage along evacuation routes,,Planning and Regulatory,,Upgrade signage along evacuation routes,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Jeffersonville,,,,,,Village DPW/Highway DOT (HW Work Permit),Village DPW/Highway DOT (HW Work Permit),Village DPW/Highway DOT (HW Work Permit),,,,,Moderate,,,yes,Existing and new,,,yes,,Moderate,,,,,,,,"Local (Muni.), County","Municipal Budget, County Funds",,,,,4,,,,,,,,,,,
Improve emergency vehicle access and response time,,Planning and Regulatory,,Extend Lovett Lane to Swiss Hill to improve emergency vehicle access and response time,All Hazards,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Jeffersonville,,,,,,Village DPW/Highway,Village DPW/Highway,Village DPW/Highway,,,,,Long,,,yes,Existing and new,,,,,High,,,,,,,,Local (Muni.),Municipal Budget,,,,,"1,4",,,,,,,,,,,
IAssess and maintain condition of box culverts on private property,,Prevention/Mitigation projects,,Implement program to assess and maintain condition of box culverts on private property,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Liberty,,yes,yes,,,Village DPW/Highway,Village DPW/Highway,Village DPW/Highway,,,,,Long,,,,Existing,,,,,Moderate,,,,,,,,Local (Muni.),Municipal Budget,,,,,"1,2",,,,,,,,,,,
Replace/rehab roads/bridges to minimize flood damage,,Prevention/Mitigation projects,,"Replace/rehab West St. Bridge, Park&Rec parking lot culvert, Church St. to minimize flood damage","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Liberty,,yes,yes,,,Village DPW/Highway,Village DPW/Highway,Village DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Budget",,,,,"1,2",,,,,,,,,,,
Monitor condition of sewer mains,,Technical assistance/program management,,Initiate program to monitor condition of sewer mains to avoid discharge of effluent (water contam.),Civil Unrest,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Liberty,,,,,,Village DPW/Highway,Village DPW/Highway,Village DPW/Highway,,,,,Moderate,,,yes,Existing and new,,,,,High,,,,,,,,Local (Muni.),Municipal Budget,,,,,3,,,,,,,,,,,
Monitor privately-owned dams to avoid failures,,Planning/Prevention,,Execute program to monitor privately-owned dams to avoid failures,"Dam Failure, Flood",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Liberty,,,yes,,,Town Board,Town Board,Town Board,,,,,Moderate,,,,Existing,,,,,Moderate,,,,,,,,"State,Federal","HMGP, State Grant",,,,,"1,2,3",,,,,,,,,,,
Acquire emergency generator(s),,Technical assistance/program management,,Acquire emergency generators for multiple critical facilities,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Liberty,,,,,,Town Board,Town Board,Town Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Improve/upgrade stromwater drainage system,,Planning and Regulatory,,Improve/upgrade stromwater drainage system from St. John's St to Spring St,Flood,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Monticello,,yes,yes,,,Village DPW/Planning,Village DPW/Planning,Village DPW/Planning,,,,,Long,,,yes,Existing and new,,,,,Moderate,,,,,,,,"Local (Muni.), State","Municipal Budget, State Grant",,,,,"2,5",,,,,,,,,,,
Relocate DPW fuel storage tanks,,Risk/Vulnerability Assessment (and planning?),,Remove DPW fuel storage tanks,"Fire, Haz Mat",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Monticello,,,yes,,,"Village DPW/Highway, Engineer","Village DPW/Highway, Engineer","Village DPW/Highway, Engineer",,,,,Long,,,yes,Existing,,,,,Moderate,,,,,,yes,,"Local (Muni.), County, State","State & County Funds, Municipal Budget",,,,,5,,,,,,,,,,,
Acquire generator(s),,Technical assistance/program management,,Acquire generator for Ted Strobel Building,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Monticello,,,,,,Village Board,Village Board,Village Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"State, Local (Muni.), County","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Replace/rehab roads/bridges to minimize flooding impacts,,Prevention/Mitigation projects,,"Replace/rehab Greenfield Rd, including bridge structure, to minimize flooding impacts","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Woodbridge,,yesy,yes,,,Village DPW/Highway,Village DPW/Highway,Village DPW/Highway,,,,,Long,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Budget",,,,,"1,2",,,,,,,,,,,
Upgrade pipe culverts,,Prevention/Mitigation projects,,"Upgrade pipe culverts on Novogrodaky Rd, Dairyland Rd, Greenfield Rd, Green Ave, and Maple Ave to improve drainage and reduce roadway flooding","Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Woodbridge,,yes,yes,,,Village DPW/Highway,Village DPW/Highway,Village DPW/Highway,,,,,Long,,,,Existing,,,,,High,,,,,,,,"Local (Muni.), State, Federal","DOT, FHWA, Municipal Budget",,,,,"1,2",,,,,,,,,,,
Acquire emergency generator(s),,Technical assistance,,Acquire emergency generator for Town Hall,Utility Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Woodbridge,,,,,,Village Board,Village Board,Village Board,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State","Municipal Budget, County Budget, NYS Member Items",,,,,"4,5",,,,,,,,,,,
Park Improvements ,,Prevention/Mitigation projects,,"Improvements to Krieger Park to reduce flood damage (increase elevations, construct berms, or other site barriers, remove stream sediment to provide more flood storage)","Flood, Severe Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Woodbridge,,yes,yes,,,Village DPW/Highway,Village DPW/Highway,Village DPW/Highway,,,,,Moderate,,,yes (?),Existing,,,,,Moderate,,,,,,,,Local (Muni.),Municipal Budget,,,,,"2,3",,,,,,,,,,,
Replace/rehab roads/bridges to reduce flood damage,,Prevention/Mitigation projects,,Replace/rehab Sullivan St. Bridge to reduce flood damage,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Wurtsboro,,yes,yes,,,Village DPW/Highway,Village DPW/Highway,Village DPW/Highway,,,,,Long,,,yes,Existing,,,,,High,,,,,,,,"Local (Muni.), County, State, Federal","DOT, FHWA, Municipal Budget, County Budget",,,,,"1,2",,,,,,,,,,,
Improve stormwater drainage system,,Prevention/Mitigation projects,,Improve stormwater drainage system along Canal St to minimize flooding impacts,"Flood, Severe Storm, Winter Storm",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Wurtsboro,,yes,yes,,,"Village DPW/Highway, Planning","Village DPW/Highway, Planning","Village DPW/Highway, Planning",,,,,Moderate,,,yes,Existing,,,,,Moderate,,,,,,,,"Local (Muni.), State","Municipal Budget, State Grant",,,,,"2,5",,,,,,,,,,,
Implement a maintenance program,,,,Implement a maintenance program for debris removal from Wilsey Brook,"Dam Failure, Flood, Ice Jam",,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Wurtsboro,,,yes,,,Village DPW/Highway,Village DPW/Highway,Village DPW/Highway,,,,,Moderate,,,yes,Existing and new,,,,,Moderate,,,,,,,,"Local (Muni.), Federal, State","HMGP, SWCD, State Grant",,,,,"2,3,5",,,,,,,,,,,
Complete dam assessment,,Risk/Vulnerability Assessment,,Complete dam assessment for Masten Lake Dam,Dam Failure,,Sullivan County Multi-Jurisdictional Hazard Mititgation Plan Update 2012,"October, 2012",Sullivan,Village of Wurtsboro,,,yes,,,"Town Board, Town Planning Board","Town Board, Town Planning Board","Town Board, Town Planning Board",,,,,Moderate,,,yes,Existing,,,,,Moderate,,,,,,,,"State, Local (Muni.)","NYSDEC, Municipal Budget",,,,,"2,5",,,,,,,,,,,
*/